version : "3"
services:
  app:
    build: ./my_app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      -  db
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT_PASSWORD
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=emmanuel
      - MYSQL_PASSWORD=batmanman
